import type { Metadata } from 'next';
import { AuthProvider } from './context/AuthContext';

import './globals.css';

export const metadata: Metadata = {
  title: 'Staff Management',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-black antialiased">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
